version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "8080:80"
      - "4443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
      - ./nginx/logs:/var/log/nginx:rw
    depends_on:
      - nextjs-app
    networks:
      - app-network
    command: [ "nginx", "-g", "daemon off;" ]

  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs-app
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - prisma
    networks:
      - app-network
    environment:
      - NODE_ENV=production

  prisma:
    image: node:18-alpine
    container_name: prisma
    working_dir: /app
    volumes:
      - .:/app
    command: ["sh", "-c", "npx prisma migrate deploy && npx prisma generate"]
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge
